---
version: '3.9'
services:
  product-service:
    image: product-service:latest
    container_name: product-service
    hostname: product-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - my-network
networks:
  my-network:
      name: my-network
      external: true