version: "3.9"
services:
  sonarqube:
    image: sonarqube:community
    container_name: "sonarqube"
    hostname: "sonarqube"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      # The first default user/password is admin/admin
      SONAR_JDBC_USERNAME: ${SONAR_USERNAME}
      SONAR_JDBC_PASSWORD: ${SONAR_PASSWORD}
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs
    ports:
      - "9081:9000"
    networks:
      - my-network
networks:
  my-network:
      name: my-network
      external: true
volumes:
  sonar_data:
  sonar_extensions:
  sonar_logs:
