server:
  port: 8222
  
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
        - id: students
          uri: http://localhost:8800
          predicates:
          - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8900
          predicates:
           - Path=/api/v1/schools/**

management:
  tracing:
    sampling:
      probability: 1.0