---
version: '3.9'
services:
  inventory-service:
    image: inventory-service:latest
    container_name: inventory-service
    hostname: inventory-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - my-network
networks:
  my-network:
      name: my-network
      external: true