version: "3.9"
services:
  nifi:
    user: root
    image: apache/nifi:latest
    container_name: "nifi"
    hostname: "nifi"
    ports:
      - "9191:8181"
      # - "8443:8443"
    environment:
      NIFI_WEB_HTTP_PORT: 8181
      # NIFI_WEB_HTTPS_PORT: 8443
      # SINGLE_USER_CREDENTIALS_USERNAME: admin
      # SINGLE_USER_CREDENTIALS_PASSWORD: admin
    volumes:
      - nifi_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_logs:/opt/nifi/nifi-current/logs
      - nifi_conf:/opt/nifi/nifi-current/conf
      # For PostgreSQL use. You can remove it.
      - ./lib/postgresql-42.5.1.jar:/opt/nifi/nifi-current/lib/postgresql-42.5.1.jar
      # For my personal ETL flow practice. You can remove it.
      - ./files/addresses.csv:/opt/nifi/nifi-current/content/addresses.csv
    networks:
      - my-network
networks:
  my-network:
      name: my-network
      external: true
volumes:
  nifi_database_repository:
  nifi_flowfile_repository:
  nifi_content_repository:
  nifi_provenance_repository:
  nifi_state:
  nifi_logs:
  nifi_conf:
