server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka@localhost:8761/eureka

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger

spring:
  application:
    name: login-ui